"""Step 2b: deterministically compile a validated test plan into an actual
pytest file. This is templating, not a second AI call -- the LLM decided
*what* to test in generate_test_plan.py; turning that structured decision
into Python is a mechanical lookup from schema.py's fields to
ResponseValidator calls. That split means nothing here executes code an LLM
wrote freeform, and the "syntax check before executing" step (added in the
reliability step) has a much smaller thing to verify.

Output always lands in generated/pending/ -- pytest.ini does not collect
that directory. A human reviews the file and moves (not edits-in-place) it
into generated/approved/ to wire it into the real suite. That's the review
gate: nothing here auto-merges into what CI runs.

Usage (run from testing/):
    python ai/generate_tests.py
    python ai/generate_tests.py --plan generated/pending/test_plan.json
"""
from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ai.schema import validate_test_plan  # noqa: E402

FILE_HEADER = '''"""AUTO-GENERATED by ai/generate_tests.py from {plan_path} -- DO NOT EDIT BY HAND.
Regenerate from the plan instead. This file lives in generated/pending/ and is
NOT collected by pytest until a human reviews it and copies it into
generated/approved/ (see testing/README.md for the review workflow).
"""
import pytest

from utils.validators import ResponseValidator

ENDPOINT = "/api/yahoo/v8/finance/chart/{{symbol}}"

'''


def render_case(case: dict) -> str:
    symbol = case["symbol"]
    params = case.get("params") or {}
    expect_status_in = case.get("expect_status_in") or [200]
    expect_chart_error = bool(case.get("expect_chart_error"))
    expect_no_reflection = bool(case.get("expect_no_reflection"))

    markers = ["@pytest.mark.ai_generated"]
    if case["category"] == "security":
        markers.append("@pytest.mark.security")

    path_symbol = symbol if symbol is not None else ""
    lines = [
        "\n".join(markers),
        f"def test_{case['id']}(api_client, endpoint_recorder):",
        f'    """{case["description"]}"""',
        f"    symbol = {symbol!r}",
        f"    params = {params!r}",
        f"    endpoint_recorder(ENDPOINT.format(symbol={path_symbol!r}))",
        "",
        f"    response = api_client.get_raw(f\"/api/yahoo/v8/finance/chart/{{symbol if symbol is not None else ''}}\", params=params)",
        "",
        "    ResponseValidator.assert_no_server_error(response)",
        f"    ResponseValidator.assert_status_code(response, {set(expect_status_in)!r})",
    ]
    if expect_chart_error:
        lines += [
            "    data = ResponseValidator.assert_is_json(response)",
            "    ResponseValidator.assert_valid_error_response(data)",
        ]
    if expect_no_reflection and symbol:
        lines.append(f"    assert {symbol!r} not in response.text")
        lines.append('    assert "<script>" not in response.text')

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", default="generated/pending/test_plan.json")
    parser.add_argument("--out", default="generated/pending/test_ai_generated.py")
    args = parser.parse_args()

    with open(args.plan, encoding="utf-8") as f:
        plan = json.load(f)
    validate_test_plan(plan)

    body = FILE_HEADER.format(plan_path=args.plan)
    body += "\n\n".join(render_case(case) for case in plan["test_cases"])

    compile(body, args.out, "exec")  # fail loudly here, not at pytest collection time

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(body)

    print(f"[generate_tests] wrote {len(plan['test_cases'])} tests -> {args.out}")
    print("[generate_tests] review the file, then: pytest " + args.out)
    print("[generate_tests] once approved, copy it into generated/approved/ to wire it into the real suite")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
